config/routes.rb
StaffingSystem::Application.routes.draw do

  resources :skillsets

  devise_for :users

  root :to => 'menu#show'
  
  match 'assignments/new/:id' => 'assignments#new'

  match 'assignments/assignmember/:id'    => 'assignments#assignmember'

  match 'assignments/assigningmember/:id'    => 'assignments#assigningmember'

  match 'assignments/release/:id/:member_id'    => 'assignments#release'

  match 'ankens/upload' => 'ankens#upload'

  match 'ankens/index' => 'ankens#index'

  match 'ankens/index/:page' => 'ankens#index'

  match 'members/upload' => 'members#upload'
  
  match 'depts/upload' => 'depts#upload'

  match 'members_by_shell' => 'members#index_by_shell'    

  match 'members_on_grid' => 'members#index_on_grid'    

  resources :skillset_roles

  resources :members

  resources :skillset_langs

  resources :skillset_rolls

  resources :depts

  resources :ankenstatuses

  resources :assignments

  resources :ankens

end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def show
  end
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/views/menu/show.html.erb
<h1><b>メインメニュー</b></h1>
<br>
<%= link_to '案件一覧', ankens_path %>
<br>
<p><%= link_to 'メンバー一覧', members_path %></p>
<p><%= link_to 'テスト　メンバー一覧(シェル)', 'members_by_shell' %></p>
<p><%= link_to 'テスト　メンバー一覧(シェルで抽出してグリッド表示)', 'members_on_grid' %></p>
<br>
<br>
<br>
<b>マスタ管理</b>
<br>
<p><%= link_to '部門管理', depts_path %></p>
<p><%= link_to 'スキル管理', skillsets_path %></p>
<br>
<br>
<br>