config/routes.rb
StaffingSystem::Application.routes.draw do

  resources :skillsets

  devise_for :users

  root :to => 'menu#show'
  
  match 'assignments/new/:id' => 'assignments#new'

  match 'assignments/assignmember/:id'    => 'assignments#assignmember'

  match 'assignments/assigningmember/:id'    => 'assignments#assigningmember'

  match 'assignments/release/:id/:member_id'    => 'assignments#release'

  match 'ankens/upload' => 'ankens#upload'

  match 'ankens/index' => 'ankens#index'

  match 'ankens/index/:page' => 'ankens#index'

  match 'members/upload' => 'members#upload'
  
  match 'depts/upload' => 'depts#upload'

  match 'members_by_shell' => 'members#index_by_shell'    

  match 'members_on_grid' => 'members#index_on_grid'    

  resources :skillset_roles

  resources :members

  resources :skillset_langs

  resources :skillset_rolls

  resources :depts

  resources :ankenstatuses

  resources :assignments

  resources :ankens

end

app/models/dept.rb
require 'csv'
class Dept < ActiveRecord::Base
  attr_accessible :code, :name
  
  validates :code, :presence => true, :uniqueness => true

  def self.to_csv(options = {})
    CSV.generate(options) do | csv |
      csv << [ "code", "name" ]
      all.each do | dept |
        row = Array.new
        row.push(dept.code.encode("Shift_JIS"))
        row.push(dept.name.encode("Shift_JIS"))
        csv << row
      end
    end
  end
  
  def self.from_csv(anArray)
    d = new
    d.code  = anArray[0]
    d.name  = anArray[1].to_s.encode('utf-8', 'sjis')
    return d    
  end

end

app/controllers/depts_controller.rb
# encording: UTF-8
class DeptsController < ApplicationController
  # GET /depts
  # GET /depts.json
  def index
    @depts = Dept.paginate(:page => params[:page], :order => 'code', :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
      format.csv { send_data Dept.to_csv }
      format.json { render json: @depts }
    end
  end

  # GET /depts/1
  # GET /depts/1.json
  def show
    @dept = Dept.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dept }
    end
  end

  # GET /depts/new
  # GET /depts/new.json
  def new
    @dept = Dept.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dept }
    end
  end

  # GET /depts/1/edit
  def edit
    @dept = Dept.find(params[:id])
  end

  # POST /depts
  # POST /depts.json
  def create
    @dept = Dept.new(params[:dept])

    respond_to do |format|
      if @dept.save
        format.html { redirect_to @dept, notice: 'Dept was successfully created.' }
        format.json { render json: @dept, status: :created, location: @dept }
      else
        format.html { render action: "new" }
        format.json { render json: @dept.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /depts/1
  # PUT /depts/1.json
  def update
    @dept = Dept.find(params[:id])

    respond_to do |format|
      if @dept.update_attributes(params[:dept])
        format.html { redirect_to @dept, notice: 'Dept was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dept.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /depts/1
  # DELETE /depts/1.json
  def destroy
    @dept = Dept.find(params[:id])
    @dept.destroy

    respond_to do |format|
      format.html { redirect_to depts_url }
      format.json { head :no_content }
    end
  end
  
  # CSV Upload /upload
  def upload
    require 'csv'
	  if !params[:upload_file].blank?
	    reader = params[:upload_file].read
	    CSV.parse(reader) do |row|
	      d = Dept.from_csv(row)
	      d.save()
	    end
	  end
	  redirect_to :action => :index
  end
  
end

app/helpers/depts_helper.rb
module DeptsHelper
end

app/views/depts/_form.html.erb
<%= form_for(@dept) do |f| %>
  <% if @dept.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dept.errors.count, "error") %> prohibited this dept from being saved:</h2>

      <ul>
      <% @dept.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/depts/edit.html.erb
<h1>部門の編集</h1>

<%= render 'form' %>

<%= link_to '表示', @dept %> |
<%= link_to '部門一覧', depts_path %>

app/views/depts/index.html.erb
<h1部門一覧</h1>

<table class="table">
  <tr>
    <th>部門コード</th>
    <th>部門名</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @depts.each do |dept| %>
  <tr>
    <td><%= dept.code %></td>
    <td><%= dept.name %></td>
    <td><%= link_to '表示', dept %></td>
    <td><%= link_to '編集', edit_dept_path(dept) %></td>
    <td><%= link_to '削除', dept, method: :delete, data: { confirm: '削除してよろしいですか？' } %></td>
  </tr>
<% end %>
  <tr>
    <td></td> <td></td> <td colspan="2"><%= link_to '部門追加', new_dept_path %></td> <td><%= link_to 'CSVダウンロード', depts_path(format:"csv") %></td>
  </tr>
</table>
<%= will_paginate @members, :previous_label=>'≪前', :next_label=>'次≫' %>

<br />
<br />
<%= form_tag 'depts/upload', :multipart => true do %>
  部門一括登録:（*.csv）
  <%= file_field_tag 'upload_file', :accept => 'text/comma-separated-values' %>
  <%= submit_tag "アップロード", :confirm => "アップロードしていいですか？" %>
<% end %>

app/views/depts/new.html.erb
<h1>部門の追加</h1>

<%= render 'form' %>

<%= link_to '部門一覧', depts_path %>

app/views/depts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>部門コード:</b>
  <%= @dept.code %>
</p>

<p>
  <b>部門名:</b>
  <%= @dept.name %>
</p>


<%= link_to '部門の編集', edit_dept_path(@dept) %> |
<%= link_to '部門一覧', depts_path %>