config/routes.rb
StaffingSystem::Application.routes.draw do

  resources :skillsets

  devise_for :users

  root :to => 'menu#show'
  
  match 'assignments/new/:id' => 'assignments#new'

  match 'assignments/assignmember/:id'    => 'assignments#assignmember'

  match 'assignments/assigningmember/:id'    => 'assignments#assigningmember'

  match 'assignments/release/:id/:member_id'    => 'assignments#release'

  match 'ankens/upload' => 'ankens#upload'

  match 'ankens/index' => 'ankens#index'

  match 'ankens/index/:page' => 'ankens#index'

  match 'members/upload' => 'members#upload'
  
  match 'depts/upload' => 'depts#upload'

  match 'members_by_shell' => 'members#index_by_shell'    

  match 'members_on_grid' => 'members#index_on_grid'    

  resources :skillset_roles

  resources :members

  resources :skillset_langs

  resources :skillset_rolls

  resources :depts

  resources :ankenstatuses

  resources :assignments

  resources :ankens

end

app/models/anken.rb
class Anken < ActiveRecord::Base
  attr_accessible :customer, :estimatePrice, :memo, :name, :ankenstatus_id, :dept_id

  has_many :assignments
  belongs_to :ankenstatus
  belongs_to :dept

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << ["dept", "name", "customer", "estimatePrice", "ankenstatus", "memo"]
      all.each do | anken |
        row = Array.new
        row.push(anken.dept_id)
        row.push(anken.dept.name.encode("Shift_JIS"))
        row.push(anken.name.encode("Shift_JIS"))
        row.push(anken.customer.encode("Shift_JIS"))
        row.push(anken.estimatePrice)
        row.push(anken.ankenstatus.name.encode("Shift_JIS"))
        row.push(anken.memo.encode("Shift_JIS"))
        csv << row
      end
    end
  end
  
  def self.from_csv(anArray)
    newAnken = new
    newAnken.dept_id         = anArray[0].to_i
    newAnken.name            = anArray[2].to_s.encode('utf-8', 'sjis')
    newAnken.customer        = anArray[3].to_s.encode('utf-8', 'sjis')
    newAnken.estimatePrice   = anArray[4].to_i
    newAnken.ankenstatus_id  = 1
    newAnken.memo            = anArray[6].to_s.encode('utf-8', 'sjis')
    return newAnken    
  end
  
end

app/controllers/ankens_controller.rb
# encording: UTF-8
class AnkensController < ApplicationController

  # GET /ankens
  # GET /ankens.json
  def index

    # 1.初期表示（メニューなどからの遷移時）
    #    ログインユーザの部門コードのみを条件に抽出
    #    ①検索条件のクリア
    #    ②ログインユーザの部門コードという条件のみセッションへの保存
    # 2.検索ボタン押下時
    #    画面入力された条件に対して抽出
    #    ①検索条件のクリア
    #    ②画面入力された条件のセッションへの保存
    # 3.ページ繰り時
    #    直前の検索条件をもとにページ繰り
    #    ①検索条件のセッションからの取り出し

    if params[:page].nil?
      # ページ繰り以外
      @searched = Hash.new()
      session[:searched] = @searched
      if params[:commit].nil?
        # 初期表示時：ログインユーザの部門コードという条件のみセッションへの保存
        @searched.store('dept_id', current_user.dept_id)
      else
        # 検索ボタン押下時：画面入力された条件のセッションへの保存
        params[:search].each do | key, value |
          @searched.store(key, value)
        end
      end
    else
      # ページ繰り時：検索条件のセッションからの取り出し
      @searched = session[:searched]
    end
    # まずはページングを指示
    @ankens = Anken.paginate(:page => params[:page], :order => 'id', :per_page => 10)
    
    # 検索条件が指定されていれば、抽出条件としてwhere句を追加
    # 部門コード
    if !(@searched.fetch('dept_id', nil).blank?)
      @ankens = @ankens.where('ankens.dept_id = ?', @searched.fetch('dept_id'))
    end
    # 案件名
    if !(@searched.fetch('ankenname', nil).blank?)
      @ankens = @ankens.where('ankens.name like ?', "%" + @searched.fetch('ankenname') + "%")
    end
    # お客様名
    if !(@searched.fetch('customer', nil).blank?)
      @ankens = @ankens.where('ankens.customer like ?', "%" + @searched.fetch('customer') + "%")
    end
    
    # ドロップリスト用
    @depts  = Dept.all()
    	    
    respond_to do |format|
      format.html # index.html.erb
      format.csv  { send_data Anken.to_csv }
      format.json { render json: @ankens }
    end
  end

  # GET /ankens/1
  # GET /ankens/1.json
  def show
    @anken = Anken.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @anken }
    end
  end

  # GET /ankens/new
  # GET /ankens/new.json
  def new
    @anken = Anken.new
		@ankenstatuses = Ankenstatus.all()
		@depts = Dept.all()
		
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @anken }
    end
  end

  # GET /ankens/1/edit
  def edit
    @anken = Anken.find(params[:id])
		@ankenstatuses = Ankenstatus.all()
		@depts = Dept.all()
  end

  # POST /ankens
  # POST /ankens.json
  def create
    @anken = Anken.new(params[:anken])

    respond_to do |format|
      if @anken.save
        format.html { redirect_to @anken, notice: 'Anken was successfully created.' }
        format.json { render json: @anken, status: :created, location: @anken }
      else
        format.html { render action: "new" }
        format.json { render json: @anken.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ankens/1
  # PUT /ankens/1.json
  def update
    @anken = Anken.find(params[:id])

    respond_to do |format|
      if @anken.update_attributes(params[:anken])
        format.html { redirect_to @anken, notice: 'Anken was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @anken.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ankens/1
  # DELETE /ankens/1.json
  def destroy
    @anken = Anken.find(params[:id])
    @anken.destroy

    respond_to do |format|
      format.html { redirect_to ankens_url }
      format.json { head :no_content }
    end
  end

  # CSV Upload /upload
  def upload
    require 'csv'
	  if !params[:upload_file].blank?
	    reader = params[:upload_file].read
	    CSV.parse(reader) do |row|
	      d = Anken.from_csv(row)
	      d.save()
	    end
	  end
	  redirect_to :action => :index
  end

end

app/helpers/ankens_helper.rb
module AnkensHelper
	def new_assignment_with(anken)
		"/assignments/new/#{anken.id}"
	end
end

app/views/ankens/_form.html.erb
<%= form_for(@anken) do |f| %>
  <% if @anken.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@anken.errors.count, "error") %> prohibited this anken from being saved:</h2>

      <ul>
      <% @anken.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :customer %><br />
    <%= f.text_field :customer %>
  </div>
  <div class="field">
    <%= f.label :estimatePrice %><br />
    <%= f.number_field :estimatePrice %>
  </div>
  <div class="field">
    <%= f.label :memo %><br />
    <%= f.text_field :memo %>
  </div>
  <div class="field">
    <%= f.label :ankenstatus %><br>
    <%= f.collection_select( :ankenstatus_id, @ankenstatuses, :id, :name, :include_blank => false ) %>
  </div>
  <div class="field">
    <%= f.label :dept %><br>
    <%= f.collection_select( :dept_id, @depts, :id, :name, :include_blank => false ) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/ankens/edit.html.erb
<h1>案件情報の編集</h1>

<%= render 'form' %>

<%= link_to '案件詳細', @anken %> |
<%= link_to '案件一覧', ankens_path %>

app/views/ankens/index.html.erb
<h1 class="title">案件一覧</h1>
<h3><b>検索条件</b></h3>
<%= form_tag "/ankens/index" do %>
<table id = "square">
  <tr>
    <td width="80" >部門     </td>
    <td width="120"><%= collection_select(:search, :dept_id, @depts, :id, :name, :include_blank => true, :selected => @searched.fetch('dept_id', ""))%></td>
  </tr>
  <tr>
    <td width="80" >案件名   </td>
    <td width="120"><%= text_field :search, :ankenname, :value => @searched.fetch('ankenname', "") %><br /></td>
    <td width="80" >お客様名   </td>
    <td width="120"><%= text_field :search, :customer, :value => @searched.fetch('customer', "") %><br /></td>
  </tr>
</table>
<%= submit_tag "検索" %>
<br />
<br />
<% end %>
<br />
<table class="table">
  <tr>
    <th>案件名</th>
    <th>お客様</th>
    <th>想定受注金額</th>
    <th>メモ</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ankens.each do |anken| %>
  <tr>
    <td><%= anken.name %></td>
    <td><%= anken.customer %></td>
    <td><%= anken.estimatePrice %></td>
    <td><%= anken.memo %></td>
    <td><%= link_to '詳細', anken %></td>
    <td><%= link_to '編集', edit_anken_path(anken) %></td>
    <td><%= link_to '削除', anken, method: :delete, data: { confirm: '削除してよろしいですか？' } %></td>
  </tr>
<% end %>
  <tr>
  <td colspan="4"></td><td colspan="2"><%= link_to '案件追加', new_anken_path %></td><td><%= link_to 'CSVダウンロード', ankens_path(format:"csv") %></td>
  </tr>
</table>
<%= will_paginate @ankens, :previous_label=>'≪前', :next_label=>'次≫' %>

<br />
<br />
<%= form_tag 'ankens/upload', :multipart => true do %>
  案件一括登録:（*.csv）
  <%= file_field_tag 'upload_file', :accept => 'text/comma-separated-values' %>
  <%= submit_tag "アップロード", :confirm => "アップロードしていいですか？" %>
<% end %>

app/views/ankens/new.html.erb
<h1>案件追加</h1>

<%= render 'form' %>

<%= link_to '案件一覧', ankens_path %>

app/views/ankens/show.html.erb
<p id="notice"><%= notice %></p>

<h2>案件情報</h2>

<div class="box">
<p>
  <b>案件名:</b>
  <%= @anken.name %>
</p>

<p>
  <b>お客様:</b>
  <%= @anken.customer %>
</p>

<p>
  <b>想定受注金額:</b>
  <%= @anken.estimatePrice %>
</p>

<p>
  <b>メモ:</b>
  <%= @anken.memo %>
</p>

<p>
  <b>ステータス:</b>
  <%= @anken.ankenstatus.name %>
</p>

<p>
  <b>主管部署:</b>
  <%= @anken.dept.name %>
</p>
<p>
<%= link_to '案件情報の編集', edit_anken_path(@anken) %>
</p>
</div>
<br />
<h3>ご要望事項</h3>
<table class="table">
  <tr>
    <th>From</th>
    <th>To</th>
    <th>役割</th>
    <th>ご要望要員数</th>
    <th>アサイン済要員数</th>
    <th>ステータス</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @anken.assignments.each do |assignment| %>
  <tr>
    <td><%= assignment.from_ymd %></td>
    <td><%= assignment.to_ymd %></td>
    <td><%= assignment.roleComment %></td>
    <td><%= assignment.num_engineer %></td>
    <td><%= assignment.members.size %></td>    
    <td><%= assignment.status %></td>
    <td><%= link_to '詳細', assignment %></td>
    <td><%= link_to '編集', edit_assignment_path(assignment) %></td>
    <td><%= link_to '削除', assignment, method: :delete, data: { confirm: '削除してよろしいですか？' } %></td>
  </tr>
<% end %>
    <tr> <td></td> <td></td> <td></td> <td></td> <td></td> <td></td> <td></td> <td></td>
    <td>
    <%= link_to 'ご要望事項の追加', new_assignment_with(@anken) %>
    </td></tr>
</table>
<br>
<%= link_to '案件一覧', ankens_path %>