config/routes.rb
StaffingSystem::Application.routes.draw do

  resources :skillsets

  devise_for :users

  root :to => 'menu#show'
  
  match 'assignments/new/:id' => 'assignments#new'

  match 'assignments/assignmember/:id'    => 'assignments#assignmember'

  match 'assignments/assigningmember/:id'    => 'assignments#assigningmember'

  match 'assignments/release/:id/:member_id'    => 'assignments#release'

  match 'ankens/upload' => 'ankens#upload'

  match 'ankens/index' => 'ankens#index'

  match 'ankens/index/:page' => 'ankens#index'

  match 'members/upload' => 'members#upload'
  
  match 'depts/upload' => 'depts#upload'

  match 'members_by_shell' => 'members#index_by_shell'    

  match 'members_on_grid' => 'members#index_on_grid'    

  resources :skillset_roles

  resources :members

  resources :skillset_langs

  resources :skillset_rolls

  resources :depts

  resources :ankenstatuses

  resources :assignments

  resources :ankens

end

app/models/member.rb
# encording: UTF-8
class Member < ActiveRecord::Base

  attr_accessible :code, :email, :name

  validates :code, :presence => true, :uniqueness => true
  
  has_and_belongs_to_many :assignments
  has_many :skill_evaluations
  has_many :skillsets, through: :skill_evaluations

  # CSVの1行に変換する
  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << ["code", "name", "email"]
      all.each do | member |
        row = Array.new
        row.push(member.code.encode("Shift_JIS"))
        row.push(member.name.encode("Shift_JIS"))
        row.push(member.email.encode("Shift_JIS"))
        csv << row
      end
    end
  end
  
  # CSVの1行をもとにインスタンスを作って返す
  def self.from_csv(anArray)
    m = new
    m.code  = anArray[0]
    m.name  = anArray[1].to_s.encode('utf-8', 'sjis')
    m.email = anArray[2]
    return m    	
  end
  
  # 
  def all_skillEvaluations
    work_skillsets = Array.new()
    #self.skillsets.each do | s |
    #  puts s.name	
    #end
    self.skill_evaluations.each do | eval |
      work_skillsets.push(eval.skillset)
    end
    
    Skillset.all().each do | skillset |
      if work_skillsets.index(skillset).nil?
        new_eval = self.skill_evaluations.new()
        new_eval.skillset = skillset
        new_eval.evaluation = ''
        new_eval.save()
      end
    end
    return self.skill_evaluations.sort_by{ |model| model.skillset.id }   
  end
  
  def asTimelineRows
    anArray = Array.new()
    self.assignments.each do | anAssignment |
      anArray.push(anAssignment.asTimelineRow)
    end
    return anArray
  end
  
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  include Kinukake
  
  # GET /members
  # GET /members.json
  
  def index
    @members = Member.paginate(:page => params[:page], :order => 'code', :per_page => 10)
    @skillsets = Skillset.all.sort_by{ |model| model.id }  
    respond_to do |format|
      format.html # index.html.erb
      format.csv { send_data Member.to_csv }
      format.json { render json: @members }
    end
  end

  # GET /members
  # GET /members.json
  
  def index_by_shell    
    respond_to do |format|
      format.html # index.html.erb
      format.csv { send_data Member.to_csv }
      format.json {  render :text =>  run2('EXTRACT_MEMBERS.sh', 'JSON', params[:rows], params[:page]) }
    end  
  
  end
  
  def index_on_grid

    @columns = ['code', 'name', 'email']

    @members = Member.paginate(
      :page     => params[:page],
      :per_page => params[:rows],
      :order    => order_by_from_params(params))

    respond_to do |format|
      format.html # index.html.erb
      format.json {
        puts json_for_jqgrid(@members, @columns) 
        render :json => json_for_jqgrid(@members, @columns) 
        }
    end
    
  end
  
  # GET /members/1
  # GET /members/1.json
  def show
    @member = Member.find(params[:id])

	  # data for google timeline chart
	  gon.graph_data = @member.asTimelineRows()
	  #puts gon.graph_data

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/new
  # GET /members/new.json
  def new
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(params[:member])

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render json: @member, status: :created, location: @member }
      else
        format.html { render action: "new" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.json
  def update
    @member = Member.find(params[:id])

    params[:skillset].each do | id, evaluation |
      skillEvaluation = SkillEvaluation.find(id)
      if skillEvaluation
        skillEvaluation.evaluation = evaluation
        skillEvaluation.save()
      end
    end
    
    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end
  
  # CSV Upload /upload
  def upload
    require 'csv'
	  if !params[:upload_file].blank?
	    reader = params[:upload_file].read
	    CSV.parse(reader) do |row|
	      m = Member.from_csv(row)
	      m.save()
	    end
	  end
	  redirect_to :action => :index
  end
  
end

app/helpers/members_helper.rb
module MembersHelper

  include Kinukake

  include JqgridsHelper

  def members_jqgrid

    grid = [{
#      :url => '/members_on_grid', # Rubyによるデータ抽出
      :url => '/members_by_shell', # シェルによるデータ抽出
      :datatype => 'json',
      :mtype => 'GET',
      :colNames => ['code','name','email'],
      :colModel  => [
        { :name => 'code',   :index => 'code',  :width => 180 },
        { :name => 'name',   :index => 'name',  :width => 240 },
        { :name => 'email',  :index => 'email', :width => 300 }
      ],
      :pager => '#members_pager',
      :rowNum => 10,
      :rowList => [10, 20, 30],
      :caption => 'Members List',
      :onSelectRow => "function() { alert('Row selected!');}".to_json_var
    }]

    jqgrid_api 'members_list', grid
  end

end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <br>
  <table>
    <% @member.all_skillEvaluations.each do | eval | %>
    <tr>
    <td><%= eval.skillset.name %></td>
    <td><%= select_tag 'skillset[' + eval.id.to_s + ']', options_for_select(['　','○','△','×'], eval.evaluation) %></td>
    </tr>
    <% end %>
  </table>
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>メンバの編集</h1>

<%= render 'form' %>

<%= link_to '表示', @member %> |
<%= link_to 'メンバ一覧', members_path %>

app/views/members/index.html.erb
<h1>メンバ一覧</h1>

<table class="table" >
  <tr>
    <th>社員コード</th>
    <th>姓名</th>
    <th>Ｅメール</th>
    <% @skillsets.each do | skillset | %>
      <th><%= skillset.name %></th>
    <% end %>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @members.each do |member| %>
  <tr>
    <td><%= member.code %></td>
    <td><%= member.name %></td>
    <td><%= member.email %></td>
    <% member.all_skillEvaluations.each do | eval | %>
      <td><%= eval.evaluation %></td>
    <% end %>
    <td><%= link_to '詳細', member %></td>
    <td><%= link_to '編集', edit_member_path(member) %></td>
    <td><%= link_to '削除', member, method: :delete, data: { confirm: '削除してよろしいですか？' } %></td>
  </tr>
<% end %>
  <tr>
  <td colspan="3"></td>
  <td colspan="2"><%= link_to '新規メンバー', new_member_path %></td>
  <td colspan="1"><%= link_to 'CSVダウンロード', members_path(format:"csv") %></td>
  </tr> 
</table>
<%= will_paginate @members, :previous_label=>'≪前', :next_label=>'次≫' %>
<br />
<br />
<%= form_tag 'members/upload', :multipart => true do %>
  メンバー一括登録:（*.csv）
  <%= file_field_tag 'upload_file', :accept => 'text/comma-separated-values' %>
  <%= submit_tag "アップロード", :confirm => "アップロードしていいですか？" %>
<% end %>
<br />

app/views/members/index_by_shell.html.erb
<h1>メンバ一覧</h1>

<table class="table">
  <thead>
    <tr>
      <th>社員コード</th>
      <th>姓名</th>
      <th>Ｅメール</th>
    </tr>
  </thead>

  <tbody>
    <%= raw(run('EXTRACT_MEMBERS.sh', 'HTML')) %>
  </tbody>
  
</table>
<br />

app/views/members/index_on_grid.html.erb
<h1>Listing Members</h1>
<table id="members_list"></table>
<div id="members_pager"></div>
<%= raw(members_jqgrid) %>

app/views/members/new.html.erb
<h1>メンバ追加</h1>

<%= render 'form' %>

<%= link_to 'メンバ一覧', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b class="label">社員コード:</b>
  <%= @member.code %>
</p>

<p>
  <b>姓名:</b>
  <%= @member.name %>
</p>

<p>
  <b>Ｅメール:</b>
  <%= @member.email %>
</p>

<table>
  <% @member.all_skillEvaluations.each do | eval | %>
    <tr>
    <td><%= eval.skillset.name %></td>
    <td><%= eval.evaluation %></td>
    </tr>
  <% end %>
</table>

<p>
<%= link_to 'メンバの編集', edit_member_path(@member) %>
</p>

<br/>
<p>
  <b><%= @member.name %>さんのアサイン状況</b>
	<table class="table">
	  <tr>
	    <th>From</th>
	    <th>To</th>
	    <th>案件名</th>    
	    <th>お客様</th>    
	    <th>役割</th>
	    <th>案件スタータス</th>
	    <th></th>
	    <th></th>
	    <th></th>
	  </tr>
	  <% @member.assignments.each do |assignment| %>
	  <tr>
	    <td><%= assignment.from_ymd %></td>
	    <td><%= assignment.to_ymd %></td>
	    <td><%= assignment.anken.name %></td>
	    <td><%= assignment.anken.customer %></td>
	    <td><%= assignment.roleComment %></td>
	    <td><%= assignment.status %></td>
	    <td><%= link_to '詳細', assignment %></td>
	    <td><%= link_to '編集', edit_assignment_path(assignment) %></td>
	    <td><%= link_to 'リリース', '/assignments/release/' + assignment.id.to_s + '/' + @member.id.to_s, data: { confirm: 'リリースしてよろしいですか？' } %></td>
	  </tr>
	  <% end %>
	</table>
</p>
<br />
<div id="chart_div"></div>
<br />

<%= raw(run('EXTRACT_ASSIGNS.sh', @member.id, 'JSON' )) %>

<%= link_to 'メンバ一覧', members_path %>

app/views/members/show_old.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b class="label">社員コード:</b>
  <%= @member.code %>
</p>

<p>
  <b>姓名:</b>
  <%= @member.name %>
</p>

<p>
  <b>Ｅメール:</b>
  <%= @member.email %>
</p>

<table>
  <% @member.all_skillEvaluations.each do | eval | %>
    <tr>
    <td><%= eval.skillset.name %></td>
    <td><%= eval.evaluation %></td>
    </tr>
  <% end %>
</table>

<p>
<%= link_to 'メンバの編集', edit_member_path(@member) %>
</p>

<br/>
<p>
  <b><%= @member.name %>さんのアサイン状況</b>
	<table class="table">
	  <tr>
	    <th>From</th>
	    <th>To</th>
	    <th>案件名</th>    
	    <th>お客様</th>    
	    <th>役割</th>
	    <th>案件スタータス</th>
	    <th></th>
	    <th></th>
	    <th></th>
	  </tr>
	  <% @member.assignments.each do |assignment| %>
	  <tr>
	    <td><%= assignment.from_ymd %></td>
	    <td><%= assignment.to_ymd %></td>
	    <td><%= assignment.anken.name %></td>
	    <td><%= assignment.anken.customer %></td>
	    <td><%= assignment.roleComment %></td>
	    <td><%= assignment.status %></td>
	    <td><%= link_to '詳細', assignment %></td>
	    <td><%= link_to '編集', edit_assignment_path(assignment) %></td>
	    <td><%= link_to 'リリース', '/assignments/release/' + assignment.id.to_s + '/' + @member.id.to_s, data: { confirm: 'リリースしてよろしいですか？' } %></td>
	  </tr>
	  <% end %>
	</table>
</p>
<br />
<div id="chart_div"></div>
<br />

<!------------------------------------------------------------------------>
<!-- AJAX API のロード -->
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">

// Visualization API と折れ線グラフ用のパッケージのロード
google.load("visualization", "1", {packages:["timeline"]});

// Google Visualization API ロード時のコールバック関数の設定
google.setOnLoadCallback(drawChart);

// グラフ作成用のコールバック関数
function drawChart() {

	// データテーブルの作成
	var dataTable = new google.visualization.DataTable();

    dataTable.addColumn({ type: 'string', id: 'anken' });
    dataTable.addColumn({ type: 'string', id: 'role' });
    dataTable.addColumn({ type: 'date', id: 'Start' });
    dataTable.addColumn({ type: 'date', id: 'End' });
    
    for (var row in gon.graph_data){
 	      dataTable.addRow([ gon.graph_data[row][0], gon.graph_data[row][1], new Date(gon.graph_data[row][2], gon.graph_data[row][3], gon.graph_data[row][4]),  new Date(gon.graph_data[row][5], gon.graph_data[row][6], gon.graph_data[row][7]) ])
      }
    
    //dataTable.addRows(gon.graph_data)

	// グラフのオプションを設定
	var options = { title: '会社業績' };
    
	// LineChart のオブジェクトの作成
	var chart = new google.visualization.Timeline(document.getElementById('chart_div'));

	// データテーブルとオプションを渡して、グラフを描画
	chart.draw(dataTable, options);

}
</script>


<%= link_to 'メンバ一覧', members_path %>